import type { ComponentProps } from 'react';
import { Ionicons, MaterialIcons } from '@expo/vector-icons';

/**
 * The app's icon component — renders Google Material icons.
 *
 * Screens keep their existing Ionicons-style names (so every name stays type-checked); each one is drawn
 * with its Material equivalent from ION_TO_MATERIAL. Names with no Material equivalent — brand logos such
 * as WhatsApp, Instagram, Apple and Google Play — are drawn with their original brand icon.
 */
export type IconName = keyof typeof Ionicons.glyphMap;
type MaterialName = keyof typeof MaterialIcons.glyphMap;

const ION_TO_MATERIAL: Partial<Record<IconName, MaterialName>> = {
  'add': 'add',
  'add-circle-outline': 'add-circle-outline',
  'add-outline': 'add',
  'alert-circle': 'error',
  'alert-circle-outline': 'error-outline',
  'apps': 'apps',
  'apps-outline': 'apps',
  'arrow-back': 'arrow-back',
  'arrow-back-outline': 'arrow-back',
  'arrow-down': 'arrow-downward',
  'arrow-forward': 'arrow-forward',
  'arrow-forward-outline': 'arrow-forward',
  'arrow-up': 'arrow-upward',
  'barbell-outline': 'fitness-center',
  'basketball-outline': 'sports-basketball',
  'battery-charging-outline': 'battery-charging-full',
  'bed-outline': 'bed',
  'book-outline': 'menu-book',
  'bookmark': 'bookmark',
  'bookmark-outline': 'bookmark-border',
  'briefcase-outline': 'work-outline',
  'bug-outline': 'bug-report',
  'bulb-outline': 'lightbulb-outline',
  'bus': 'directions-bus',
  'bus-outline': 'directions-bus',
  'business-outline': 'business',
  'cafe-outline': 'free-breakfast',
  'calendar': 'event',
  'calendar-outline': 'event',
  'call': 'call',
  'call-outline': 'call',
  'camera': 'photo-camera',
  'camera-outline': 'photo-camera',
  'car-outline': 'directions-car',
  'car-sport-outline': 'electric-car',
  'card-outline': 'credit-card',
  'cart-outline': 'shopping-cart',
  'cash-outline': 'payments',
  'chatbubble-ellipses-outline': 'chat-bubble-outline',
  'chatbubbles-outline': 'forum',
  'checkmark': 'check',
  'checkmark-circle': 'check-circle',
  'checkmark-circle-outline': 'check-circle-outline',
  'checkmark-done-outline': 'done-all',
  'chevron-back': 'chevron-left',
  'chevron-back-outline': 'chevron-left',
  'chevron-down': 'expand-more',
  'chevron-forward': 'chevron-right',
  'chevron-forward-outline': 'chevron-right',
  'chevron-up': 'expand-less',
  'close': 'close',
  'close-circle': 'cancel',
  'close-circle-outline': 'highlight-off',
  'close-outline': 'close',
  'cloud-offline-outline': 'cloud-off',
  'color-palette-outline': 'palette',
  'compass-outline': 'explore',
  'construct-outline': 'build',
  'copy-outline': 'content-copy',
  'create-outline': 'edit',
  'document-attach-outline': 'attach-file',
  'document-outline': 'description',
  'document-text-outline': 'description',
  'ellipse': 'circle',
  'ellipse-outline': 'radio-button-unchecked',
  'ellipsis-horizontal': 'more-horiz',
  'enter-outline': 'login',
  'eye-off-outline': 'visibility-off',
  'eye-outline': 'visibility',
  'fast-food-outline': 'fastfood',
  'file-tray-full-outline': 'inbox',
  'file-tray-outline': 'inbox',
  'filter-outline': 'filter-list',
  'flash-outline': 'bolt',
  'flask-outline': 'science',
  'football-outline': 'sports-soccer',
  'gift-outline': 'card-giftcard',
  'globe-outline': 'public',
  'grid': 'grid-view',
  'grid-outline': 'grid-view',
  'hammer-outline': 'construction',
  'heart': 'favorite',
  'heart-outline': 'favorite-border',
  'help-circle-outline': 'help-outline',
  'home': 'home',
  'home-outline': 'home',
  'images': 'photo-library',
  'images-outline': 'photo-library',
  'information-circle': 'info',
  'information-circle-outline': 'info-outline',
  'key': 'vpn-key',
  'layers-outline': 'layers',
  'library-outline': 'local-library',
  'link': 'link',
  'link-outline': 'link',
  'list-outline': 'list',
  'locate-outline': 'my-location',
  'location': 'place',
  'location-outline': 'place',
  'lock-closed-outline': 'lock-outline',
  'lock-open-outline': 'lock-open',
  'mail': 'mail',
  'mail-outline': 'mail-outline',
  'map': 'map',
  'map-outline': 'map',
  'medical-outline': 'medical-services',
  'medkit': 'medical-services',
  'medkit-outline': 'medical-services',
  'megaphone': 'campaign',
  'megaphone-outline': 'campaign',
  'menu': 'menu',
  'musical-notes-outline': 'music-note',
  'navigate': 'navigation',
  'navigate-outline': 'navigation',
  'notifications': 'notifications',
  'notifications-off-outline': 'notifications-off',
  'notifications-outline': 'notifications-none',
  'open': 'open-in-new',
  'open-outline': 'open-in-new',
  'options-outline': 'tune',
  'pencil': 'edit',
  'people': 'people',
  'people-circle-outline': 'groups',
  'people-outline': 'people-outline',
  'person-circle-outline': 'account-circle',
  'person-outline': 'person-outline',
  'pin-outline': 'push-pin',
  'pricetag-outline': 'sell',
  'pricetags-outline': 'sell',
  'qr-code-outline': 'qr-code-2',
  'radio': 'sensors',
  'radio-button-off': 'radio-button-unchecked',
  'radio-button-on': 'radio-button-checked',
  'radio-outline': 'sensors',
  'refresh': 'refresh',
  'refresh-outline': 'refresh',
  'remove-circle-outline': 'remove-circle-outline',
  'remove-outline': 'remove',
  'reorder-three': 'drag-handle',
  'restaurant': 'restaurant',
  'restaurant-outline': 'restaurant',
  'ribbon-outline': 'workspace-premium',
  'scan-outline': 'crop-free',
  'school-outline': 'school',
  'search': 'search',
  'search-outline': 'search',
  'send': 'send',
  'send-outline': 'send',
  'settings': 'settings',
  'settings-outline': 'settings',
  'share-outline': 'share',
  'share-social-outline': 'share',
  'shield-checkmark-outline': 'verified-user',
  'shield-outline': 'shield',
  'shirt-outline': 'checkroom',
  'sparkles-outline': 'auto-awesome',
  'star': 'star',
  'star-outline': 'star-outline',
  'sunny': 'brightness-high',
  'sunny-outline': 'brightness-low',
  'stats-chart-outline': 'bar-chart',
  'sync-outline': 'sync',
  'ticket-outline': 'confirmation-number',
  'time-outline': 'schedule',
  'today': 'today',
  'today-outline': 'today',
  'trash-outline': 'delete-outline',
  'trophy-outline': 'emoji-events',
  'wallet-outline': 'account-balance-wallet',
  'warning': 'warning',
  'warning-outline': 'warning-amber',
  'water-outline': 'water-drop',
  'wifi': 'wifi',
  'wifi-outline': 'wifi',
};

type IconProps = Omit<ComponentProps<typeof Ionicons>, 'name'> & { name: IconName };

export function Icon({ name, ...rest }: IconProps) {
  const material = ION_TO_MATERIAL[name];
  return material ? <MaterialIcons name={material} {...rest} /> : <Ionicons name={name} {...rest} />;
}

/** Same name set as before, so `keyof typeof Icon.glyphMap` types keep working. */
Icon.glyphMap = Ionicons.glyphMap;
