/**
 * Academic calendar import (plan §8, §9.2, §10, §15).
 *
 *   npm run calendar:import -w @iitj1/api                 # DRY RUN (default) — no database connection
 *   npm run calendar:import -w @iitj1/api -- --apply --i-have-reviewed-the-dry-run
 *
 * Dry run:
 *   - normalizes the verified PDF source layer against the working JSON (fails loudly on any mismatch);
 *   - writes apps/api/src/data/academicCalendar.2026-27.json (the normalized doc, used by the offline
 *     fallback store and for review);
 *   - writes apps/api/data/academic-calendar/2026-27.import-report.md (stats, review queue, holiday plan).
 *
 * Apply (production write — only after the dry-run report has been reviewed and approved):
 *   - merges into the stored calendar without overwriting admin conflict resolutions;
 *   - upserts ONLY the confirmed in-year official holidays into the existing holidays module
 *     (never pre-AY, tentative, no-class days, breaks or Semester II); never edits/deletes existing entries.
 */
import dotenv from 'dotenv';
import path from 'path';
import { readFileSync, writeFileSync } from 'fs';
import { connectDb, disconnectDb, isDbConnected } from '../src/db';
import { getCalendar, getHolidays, getMeta, putCalendar, putHolidays } from '../src/store';
import {
  CalendarImportError,
  normalizeAcademicCalendar,
  planHolidayUpsert,
  type HolidayRecord,
  type MappingFile,
  type SourceFile,
  type WorkingFile,
} from '../src/services/academicCalendarImport';
import { mergeCalendarImport, type AcademicCalendarDoc } from '@iitj1/types';

dotenv.config({ path: path.resolve(__dirname, '../.env') });

const REPO = path.resolve(__dirname, '../../..');
const MAPPING = path.join(REPO, 'apps/api/data/academic-calendar/2026-27.mapping.json');
const NORMALIZED_OUT = path.join(REPO, 'apps/api/src/data/academicCalendar.2026-27.json');
const REPORT_OUT = path.join(REPO, 'apps/api/data/academic-calendar/2026-27.import-report.md');
const IMPORTER = 'academic-calendar-import';

function readJson<T>(file: string): T {
  return JSON.parse(readFileSync(file, 'utf8')) as T;
}

function report(doc: AcademicCalendarDoc, stats: ReturnType<typeof normalizeAcademicCalendar>['stats'], holidayPlan: string): string {
  const lines = [
    '# Academic calendar import — dry-run report (AY 2026-27)',
    '',
    `Generated by \`scripts/import-academic-calendar.ts\` (dry run). Source: ${doc.source?.file} (${doc.source?.documentDate}).`,
    'Nothing was written to any database.',
    '',
    '## Totals',
    '',
    `- Source entries (Layer 1): ${stats.sourceEntries}`,
    `- Dated PDF cells: ${stats.datedCells}, all represented: ${stats.coveredCells >= stats.datedCells ? 'yes' : 'NO'}`,
    `- Student-visible events: ${stats.events}`,
    `- Review queue (hidden until resolved): ${stats.reviewItems}`,
    `- By display type: ${Object.entries(stats.byDisplayType).map(([k, v]) => `${k} ${v}`).join(', ')}`,
    '',
    '## Review queue',
    '',
    '| Item | Kind | Candidates (verbatim, source) | Reason |',
    '| --- | --- | --- | --- |',
    ...(doc.reviewQueue ?? []).map(
      (c) =>
        `| ${c.id} | ${c.kind} | ${c.candidates.map((x) => `${x.startDate} — "${x.dateSourceText}" (${x.sourceRef}, p.${x.page})`).join('<br>')} | ${c.reason} |`,
    ),
    '',
    '## Confirmed in-year official holidays → transport holiday list',
    '',
    holidayPlan,
    '',
  ];
  return lines.join('\n');
}

async function main(): Promise<void> {
  const apply = process.argv.includes('--apply');
  const confirmed = process.argv.includes('--i-have-reviewed-the-dry-run');
  const mapping = readJson<MappingFile & { workingData: string; sourceData: string }>(MAPPING);
  const source = readJson<SourceFile>(path.join(REPO, mapping.sourceData));
  const working = readJson<WorkingFile>(path.join(REPO, mapping.workingData));

  let normalized: ReturnType<typeof normalizeAcademicCalendar>;
  try {
    normalized = normalizeAcademicCalendar(source, working, mapping);
  } catch (err) {
    if (err instanceof CalendarImportError) {
      console.error(err.message);
      process.exitCode = 1;
      return;
    }
    throw err;
  }
  const { doc, stats } = normalized;

  if (!apply) {
    // Stable output for review: the import timestamp is not part of the committed file.
    const { importedAt: _importedAt, ...stable } = doc;
    void _importedAt;
    // Only the "imported" history timestamp changes between runs; keep the committed file stable when the
    // content is otherwise identical, so a dry run never produces a noise-only diff.
    const withoutTimes = (v: unknown) =>
      JSON.stringify(v, (k, val) => (k === 'at' && typeof val === 'string' ? '' : val));
    let previous: unknown = null;
    try {
      previous = JSON.parse(readFileSync(NORMALIZED_OUT, 'utf8'));
    } catch {
      previous = null;
    }
    if (previous && withoutTimes(previous) === withoutTimes(stable)) {
      console.log(`[calendar] ${path.relative(REPO, NORMALIZED_OUT)} unchanged (content identical)`);
    } else {
      writeFileSync(NORMALIZED_OUT, `${JSON.stringify(stable, null, 2)}\n`);
      console.log(`[calendar] wrote ${path.relative(REPO, NORMALIZED_OUT)}`);
    }
    const dryPlan = planHolidayUpsert(doc, [], '1970-01-01T00:00:00.000Z');
    const holidayPlan = [
      'Planned against an EMPTY holiday list (the dry run does not read the database). On --apply the',
      'existing list is read first; entries already present (same id or same date) are linked, not duplicated.',
      '',
      '| Date | Holiday (verbatim) | Planned id |',
      '| --- | --- | --- |',
      ...dryPlan.added.map((h) => `| ${h.date} | ${h.name} | ${h.id} |`),
    ].join('\n');
    writeFileSync(REPORT_OUT, report(doc, stats, holidayPlan));
    console.log(`[calendar] DRY RUN OK — ${stats.events} events, ${stats.reviewItems} review items, ${stats.datedCells} dated cells covered.`);
    console.log(`[calendar] wrote ${path.relative(REPO, REPORT_OUT)}`);
    console.log('[calendar] No database writes. Re-run with --apply --i-have-reviewed-the-dry-run after approval.');
    return;
  }

  if (!confirmed) {
    console.error('[calendar] --apply writes to the configured MongoDB. Add --i-have-reviewed-the-dry-run to confirm.');
    process.exitCode = 1;
    return;
  }

  try {
    await connectDb();
    if (!isDbConnected()) throw new Error('MongoDB is not connected — set MONGODB_URI and retry');
    const meta = await getMeta(doc.campusId);

    const existing = (await getCalendar(doc.campusId)) as AcademicCalendarDoc | null;
    const { doc: merged, report: mergeReport } = mergeCalendarImport(existing, doc, IMPORTER);
    await putCalendar(merged as never, IMPORTER, meta.versions.calendar);
    console.log(`[calendar] calendar written: ${merged.events.length} events, ${merged.reviewQueue?.length ?? 0} review items`);
    console.log(`[calendar] kept resolutions: ${mergeReport.keptResolutions.join(', ') || 'none'}`);
    console.log(`[calendar] re-opened: ${mergeReport.reopened.map((r) => `${r.id} (${r.reason})`).join(', ') || 'none'}`);

    const holidays = await getHolidays(doc.campusId);
    const plan = planHolidayUpsert(merged, (holidays?.holidays ?? []) as HolidayRecord[]);
    if (plan.added.length) {
      await putHolidays({ campusId: doc.campusId, holidays: plan.holidays } as never, IMPORTER, meta.versions.holidays);
    }
    console.log(`[calendar] holidays added: ${plan.added.map((h) => `${h.date} ${h.name}`).join('; ') || 'none'}`);
    console.log(`[calendar] holidays linked to existing entries: ${plan.linked.map((l) => `${l.date} → ${l.existingId}`).join('; ') || 'none'}`);
  } catch (err) {
    console.error('[calendar] Failed:', (err as Error).message);
    process.exitCode = 1;
  } finally {
    await disconnectDb().catch(() => undefined);
  }
}

void main();
